version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g next
      - npm install

  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - aws s3 sync out/ s3://valleyscbucketnextjs --delete --region us-east-1
